import Header from "@/Components/Header";
import type { Metadata } from "next";
import "./../styles/globals.css";
import Provider from "./../utils/Provider";
import Footer from "@/Components/Footer";
import { api } from "./api";

export const metadata: Metadata = {
  title: "Cartify",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { data } = await api.get(
    `${process.env.NEXT_PUBLIC_STORE_BASE_URL}products/categories`
  );

  const searchTerm = "-";

  const categories = data.filter((str: string) => !str.includes(searchTerm));

  return (
    <html lang="en">
      <body className="bg-white">
        <Provider>
          <Header categories={categories} />
          {children}
          <Footer categories={categories} />
        </Provider>
      </body>
    </html>
  );
}
