import Header from "@/Components/Header";
import type { Metadata } from "next";
import "./../styles/globals.css";
import AuthProvider from "./../utils/AuthProvider";

export const metadata: Metadata = {
  title: "Cartify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
