import Header from "@/Components/Header";
import type { Metadata } from "next";
import "./../styles/globals.css";
import Provider from "./../utils/Provider";
import Footer from "@/Components/Footer";

export const metadata: Metadata = {
  title: "Cartify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <Provider>
          <Header />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
